# name: Gatsby Publish

# on:
#   push:
#     branches: [ gh-pages ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: enriikke/gatsby-gh-pages-action@v2.1.1
#       - name: Gatsby Publish
#         with:
#           access-token: ${{ secrets.data }}
#           deploy-branch: gh-pages
#           gatsby-args: --verbose