name: Gatsby Publish

on:
  push:
    branches:
      - gatsby-data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.data }}
          deploy-branch: gatsby-data
          gatsby-args: --prefix-paths